import type { Metadata } from "next";
import { ColorModeProvider } from "./context/ColorModeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ColorModeProvider>
          {children}
        </ColorModeProvider>
      </body>
    </html>
  );
}
